# For running tests locally, see check_in_container target in Makefile

FROM docker.io/usercont/packit

COPY files/install-deps.yaml ./
RUN ansible-playbook -vv -c local -i localhost, ./install-deps.yaml

COPY files/recipe-tests.yaml ./
RUN ansible-playbook -vv -c local -i localhost, ./recipe-tests.yaml

WORKDIR /src
