# For running tests locally, see check_in_container target in Makefile

FROM docker.io/usercont/packit-service-worker

RUN set -ex; mkdir -p /home/packit/.config \
    && ln -s $PS_PATH/files/packit-service.yaml /home/packit/.config/packit-service.yaml \
    && ansible-playbook -vv -c local -i localhost, ./files/recipe-tests.yaml

# we are doing the same here as in worker Df so that we don't need to rerun the
# playbook above for every code change: iterating fast <3
COPY . $PS_PATH
