"""Add a table for github installations

Revision ID: 0b4b3445f93f
Revises: d90948124e46
Create Date: 2020-03-31 13:05:16.567218

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0b4b3445f93f"
down_revision = "d90948124e46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.Column("account_login", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("account_url", sa.String(), nullable=True),
        sa.Column("account_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("repositories", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("sender_login", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("installation_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_installations")
    # ### end Alembic commands ###
