"""Adding Log Detective Run table

Revision ID: 108167f43395
Revises: d4fcd3075c10
Create Date: 2025-12-04 13:54:38.524061

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "108167f43395"
down_revision = "d4fcd3075c10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_detective_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("complete", "running", "unknown", "error", name="logdetectiveresult"),
            nullable=False,
        ),
        sa.Column("target_build", sa.String(), nullable=True),
        sa.Column("log_detective_response", sa.JSON(), nullable=True),
        sa.Column("submitted_time", sa.DateTime(), nullable=True),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column(
            "build_system", sa.Enum("copr", "koji", name="logdetectivebuildsystem"), nullable=True
        ),
        sa.Column("copr_build_target_id", sa.Integer(), nullable=True),
        sa.Column("koji_build_target_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["copr_build_target_id"], ["copr_build_targets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["koji_build_target_id"], ["koji_build_targets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("log_detective_run")
    # ### end Alembic commands ###
