"""Add SRPM link to COPR builds

Revision ID: 1bc90fcab3e1
Revises: e35bb9ce7313
Create Date: 2021-01-22 12:23:18.740971

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1bc90fcab3e1"
down_revision = "e35bb9ce7313"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("srpm_builds", sa.Column("url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("srpm_builds", "url")
    # ### end Alembic commands ###
