"""Renaming identifier column of log_detective_analysis_run

Revision ID: 22c2e7e62b56
Revises: bb4dd06bb4ab
Create Date: 2026-01-02 13:27:51.332086

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "22c2e7e62b56"
down_revision = "bb4dd06bb4ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log_detective_run", sa.Column("analysis_id", sa.String(), nullable=False))
    op.drop_constraint("log_detective_run_identifier_key", "log_detective_run", type_="unique")
    op.create_unique_constraint(None, "log_detective_run", ["analysis_id"])
    op.drop_column("log_detective_run", "identifier")
    op.alter_column(
        "log_detective_run_groups",
        "submitted_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log_detective_run_groups",
        "submitted_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.add_column(
        "log_detective_run",
        sa.Column("identifier", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "log_detective_run", type_="unique")
    op.create_unique_constraint(
        "log_detective_run_identifier_key",
        "log_detective_run",
        ["identifier"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("log_detective_run", "analysis_id")
    # ### end Alembic commands ###
