"""Create OSHScanModel

Revision ID: 242a0cdb6d23
Revises: f376be1907e1
Create Date: 2024-10-18 08:10:35.335510

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "242a0cdb6d23"
down_revision = "f376be1907e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "canceled",
                "failed",
                name="oshscanstatus",
            ),
            nullable=True,
        ),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("issues_added_url", sa.String(), nullable=True),
        sa.Column("issues_fixed_url", sa.String(), nullable=True),
        sa.Column("scan_results_url", sa.String(), nullable=True),
        sa.Column("copr_build_target_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["copr_build_target_id"],
            ["copr_build_targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("copr_build_target_id"),
        sa.UniqueConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scans")
    # ### end Alembic commands ###
