"""Add packages_config to ProjectEventModel

Revision ID: 2ad985cecd79
Revises: 7d2b9fb924fa
Create Date: 2024-04-10 13:11:48.421845

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2ad985cecd79"
down_revision = "7d2b9fb924fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_events",
        sa.Column("packages_config", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_events", "packages_config")
    # ### end Alembic commands ###
