"""Add retry to TestingFarmResult

Revision ID: 2e5ad4cbfa33
Revises: adb6be5bc358
Create Date: 2024-10-24 08:58:42.357987

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2e5ad4cbfa33"
down_revision = "adb6be5bc358"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE testingfarmresult ADD VALUE 'retry'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
