"""Store target in Koji build tag event

Revision ID: 2fdbdcd581f5
Revises: 64a51b961c28
Create Date: 2024-08-01 15:00:55.879659

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2fdbdcd581f5"
down_revision = "64a51b961c28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("koji_build_tags", sa.Column("target", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("koji_build_tags", "target")
    # ### end Alembic commands ###
