"""Add 'success' to SRPMBuildModel

Revision ID: 307a4c43ae47
Revises: c6250555a36c
Create Date: 2020-04-15 11:07:32.488213

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "307a4c43ae47"
down_revision = "f0abb806c3d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("srpm_builds", sa.Column("success", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("srpm_builds", "success")
    # ### end Alembic commands ###
