"""Add actor field for PullRequestModel

Revision ID: 30e8183b1566
Revises: a619bd414ff0
Create Date: 2022-11-23 10:45:51.677673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30e8183b1566"
down_revision = "a619bd414ff0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pull_requests", sa.Column("actor", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pull_requests", "actor")
    # ### end Alembic commands ###
