"""Extend projecteventtype

Revision ID: 3a7e4a388dd2
Revises: 002ab85fa213
Create Date: 2024-09-20 07:05:22.312528

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3a7e4a388dd2"
down_revision = "002ab85fa213"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add the event type
    op.execute("ALTER TYPE projecteventtype ADD VALUE 'anitya_multiple_versions'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
