"""Add built_packages field to CoprBuildModel

Revision ID: 3aa397e3adac
Revises: 8fee25b27402
Create Date: 2021-09-30 14:30:32.280607

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3aa397e3adac"
down_revision = "8fee25b27402"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copr_builds", sa.Column("built_packages", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copr_builds", "built_packages")
    # ### end Alembic commands ###
