"""Move to ProjectEventModelType

Revision ID: 440b8978276b
Revises: 43882376fe16
Create Date: 2025-11-19 10:55:15.341911

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "440b8978276b"
down_revision = "43882376fe16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_events",
        "type",
        existing_type=postgresql.ENUM(
            "pull_request",
            "branch_push",
            "release",
            "issue",
            "koji_build_tag",
            "anitya_version",
            "anitya_multiple_versions",
            name="projecteventtype",
        ),
        type_=sa.Enum(
            "pull_request",
            "branch_push",
            "release",
            "issue",
            "koji_build_tag",
            "anitya_version",
            "anitya_multiple_versions",
            name="projecteventmodeltype",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_events",
        "type",
        existing_type=sa.Enum(
            "pull_request",
            "branch_push",
            "release",
            "issue",
            "koji_build_tag",
            "anitya_version",
            "anitya_multiple_versions",
            name="projecteventmodeltype",
        ),
        type_=postgresql.ENUM(
            "pull_request",
            "branch_push",
            "release",
            "issue",
            "koji_build_tag",
            "anitya_version",
            "anitya_multiple_versions",
            name="projecteventtype",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
