"""Add Koji build scratch attribute

Revision ID: 46b37040cb19
Revises: 855bc0b691c2
Create Date: 2022-03-21 09:34:53.526691

"""
from alembic import op
import sqlalchemy as sa
from packit_service.models import KojiBuildTargetModel


# revision identifiers, used by Alembic.
revision = "46b37040cb19"
down_revision = "855bc0b691c2"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "koji_build_targets", sa.Column("scratch", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###

    for koji_build in session.query(KojiBuildTargetModel).all():
        koji_build.scratch = True

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("koji_build_targets", "scratch")
    # ### end Alembic commands ###
