"""Add sidetag_groups and sidetags tables

Revision ID: 487a77980f7e
Revises: 89a683a0bd51
Create Date: 2024-04-25 13:09:19.062753

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "487a77980f7e"
down_revision = "89a683a0bd51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sidetag_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sidetag_groups_name"),
        "sidetag_groups",
        ["name"],
        unique=True,
    )
    op.create_table(
        "sidetags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("koji_name", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("sidetag_group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sidetag_group_id"],
            ["sidetag_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sidetags_koji_name"),
        "sidetags",
        ["koji_name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sidetags_koji_name"), table_name="sidetags")
    op.drop_table("sidetags")
    op.drop_index(op.f("ix_sidetag_groups_name"), table_name="sidetag_groups")
    op.drop_table("sidetag_groups")
    # ### end Alembic commands ###
