"""Save propose downstream

Revision ID: 6c9e1df74fa0
Revises: 73a28911901f
Create Date: 2022-02-21 15:40:27.036358

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6c9e1df74fa0"
down_revision = "73a28911901f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "propose_downstream_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "finished",
                "error",
                name="proposedownstreamstatus",
            ),
            nullable=True,
        ),
        sa.Column("submitted_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "propose_downstream_run_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch", sa.String(), nullable=True),
        sa.Column("downstream_pr_url", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "error",
                "retry",
                "submitted",
                name="proposedownstreamtargetstatus",
            ),
            nullable=True,
        ),
        sa.Column("submitted_time", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("finished_time", sa.DateTime(), nullable=True),
        sa.Column("logs", sa.Text(), nullable=True),
        sa.Column("propose_downstream_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["propose_downstream_id"],
            ["propose_downstream_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "pipelines",
        sa.Column("propose_downstream_run_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "pipelines",
        "propose_downstream_runs",
        ["propose_downstream_run_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pipelines", type_="foreignkey")
    op.drop_column("pipelines", "propose_downstream_run_id")
    op.drop_table("propose_downstream_run_targets")
    op.drop_table("propose_downstream_runs")
    # ### end Alembic commands ###
