"""Add Koji tag request groups and targets

Revision ID: 6f936840164c
Revises: 4387d6ab90e9
Create Date: 2024-11-14 13:20:07.918410

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f936840164c"
down_revision = "f69687c314c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "koji_tag_request_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submitted_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "koji_tag_request_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("web_url", sa.String(), nullable=True),
        sa.Column("tag_request_submitted_time", sa.DateTime(), nullable=True),
        sa.Column("sidetag", sa.String(), nullable=True),
        sa.Column("nvr", sa.String(), nullable=True),
        sa.Column("koji_tag_request_group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["koji_tag_request_group_id"], ["koji_tag_request_groups.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_koji_tag_request_targets_task_id"),
        "koji_tag_request_targets",
        ["task_id"],
        unique=False,
    )
    op.add_column("pipelines", sa.Column("koji_tag_request_group_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_pipelines_koji_tag_request_group_id"),
        "pipelines",
        ["koji_tag_request_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "pipelines", "koji_tag_request_groups", ["koji_tag_request_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pipelines", type_="foreignkey")
    op.drop_index(op.f("ix_pipelines_koji_tag_request_group_id"), table_name="pipelines")
    op.drop_column("pipelines", "koji_tag_request_group_id")
    op.drop_index(
        op.f("ix_koji_tag_request_targets_task_id"), table_name="koji_tag_request_targets"
    )
    op.drop_table("koji_tag_request_targets")
    op.drop_table("koji_tag_request_groups")
    # ### end Alembic commands ###
