"""Rename whitelist to allowlist

Revision ID: 70444197d206
Revises: 1bc90fcab3e1
Create Date: 2021-01-29 16:19:20.850990

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "70444197d206"
down_revision = "1bc90fcab3e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("whitelist", "allowlist")
    op.execute("ALTER SEQUENCE whitelist_id_seq RENAME TO allowlist_id_seq")
    op.execute("ALTER INDEX whitelist_pkey RENAME TO allowlist_pkey")
    op.execute(
        "ALTER INDEX ix_whitelist_account_name RENAME TO ix_allowlist_account_name",
    )
    op.execute("ALTER TYPE whiteliststatus RENAME TO allowliststatus")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("allowlist", "whitelist")
    op.execute("ALTER SEQUENCE allowlist_id_seq RENAME TO whitelist_id_seq")
    op.execute("ALTER INDEX allowlist_pkey RENAME TO whitelist_pkey")
    op.execute(
        "ALTER INDEX ix_allowlist_account_name RENAME TO ix_whitelist_account_name",
    )
    op.execute("ALTER TYPE allowliststatus RENAME TO whiteliststatus")
    # ### end Alembic commands ###
