"""store build datetime

Revision ID: 70dcb6140e11
Revises: 258490f6e667
Create Date: 2020-03-04 16:19:09.338160

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "70dcb6140e11"
down_revision = "258490f6e667"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copr_builds",
        sa.Column("build_finished_time", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "copr_builds",
        sa.Column("build_start_time", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "copr_builds",
        sa.Column("build_submitted_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copr_builds", "build_submitted_time")
    op.drop_column("copr_builds", "build_start_time")
    op.drop_column("copr_builds", "build_finished_time")
    # ### end Alembic commands ###
