"""link srpmbuildmodel to jobtriggermodel

Revision ID: 726cb0f70c6d
Revises: adbdc1c21d7e
Create Date: 2020-08-05 18:14:20.277673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "726cb0f70c6d"
down_revision = "adbdc1c21d7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "srpm_builds", sa.Column("job_trigger_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "srpm_builds", "build_triggers", ["job_trigger_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "srpm_builds", type_="foreignkey")
    op.drop_column("srpm_builds", "job_trigger_id")
    # ### end Alembic commands ###
