"""Add bugzillas

Revision ID: 7a43773ac926
Revises: 307a4c43ae47
Create Date: 2020-06-11 07:29:27.146501

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a43773ac926"
down_revision = "307a4c43ae47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bugzillas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bug_id", sa.Integer(), nullable=True),
        sa.Column("bug_url", sa.String(), nullable=True),
        sa.Column("pull_request_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bugzillas_bug_id"), "bugzillas", ["bug_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bugzillas_bug_id"), table_name="bugzillas")
    op.drop_table("bugzillas")
    # ### end Alembic commands ###
