"""Harmonizing time stamp cols

Revision ID: 7d0ecc64ef1e
Revises: d408de018a66
Create Date: 2026-01-22 15:13:46.562282

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d0ecc64ef1e"
down_revision = "d408de018a66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("copr_build_targets", "build_submitted_time", new_column_name="submitted_time")
    op.add_column(
        "log_detective_run", sa.Column("task_accepted_time", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "tft_test_run_targets", sa.Column("task_accepted_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tft_test_run_targets", "task_accepted_time")
    op.drop_column("log_detective_run", "task_accepted_time")
    op.alter_column("copr_build_targets", "submitted_time", new_column_name="build_submitted_time")
    op.drop_column("copr_build_targets", "submitted_time")
    # ### end Alembic commands ###
