"""Add sync_release_pull_request table

Revision ID: 7d2b9fb924fa
Revises: 31111f804dec
Create Date: 2024-02-07 09:53:51.363885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d2b9fb924fa"
down_revision = "31111f804dec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_release_pull_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pr_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["git_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_release_pull_request_pr_id"),
        "sync_release_pull_request",
        ["pr_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_release_pull_request_project_id"),
        "sync_release_pull_request",
        ["project_id"],
        unique=False,
    )
    op.add_column(
        "sync_release_run_targets",
        sa.Column("downstream_pr_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "sync_release_run_targets",
        "sync_release_pull_request",
        ["downstream_pr_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sync_release_run_targets", type_="foreignkey")
    op.drop_column("sync_release_run_targets", "downstream_pr_id")
    op.drop_index(
        op.f("ix_sync_release_pull_request_project_id"),
        table_name="sync_release_pull_request",
    )
    op.drop_index(
        op.f("ix_sync_release_pull_request_pr_id"),
        table_name="sync_release_pull_request",
    )
    op.drop_table("sync_release_pull_request")
    # ### end Alembic commands ###
