"""Add fast_forward_prs column for SyncReleaseTargetModel

Revision ID: 7d2e20c5c689
Revises: e3cfec8ce0f7
Create Date: 2025-03-13 19:46:53.145958

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d2e20c5c689"
down_revision = "e3cfec8ce0f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sync_release_run_targets", sa.Column("fast_forward_prs", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sync_release_run_targets", "fast_forward_prs")
    # ### end Alembic commands ###
