"""Add models for Bodhi updates

Revision ID: 8ba13238bfa4
Revises: 3de8647515ae
Create Date: 2024-01-04 07:25:21.468683

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ba13238bfa4"
down_revision = "3de8647515ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bodhi_update_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submitted_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bodhi_update_targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("web_url", sa.String(), nullable=True),
        sa.Column("koji_nvr", sa.String(), nullable=True),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("bodhi_update_group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bodhi_update_group_id"],
            ["bodhi_update_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "pipelines",
        sa.Column("bodhi_update_group_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_pipelines_bodhi_update_group_id"),
        "pipelines",
        ["bodhi_update_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "pipelines",
        "bodhi_update_groups",
        ["bodhi_update_group_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pipelines", type_="foreignkey")
    op.drop_index(op.f("ix_pipelines_bodhi_update_group_id"), table_name="pipelines")
    op.drop_column("pipelines", "bodhi_update_group_id")
    op.drop_table("bodhi_update_targets")
    op.drop_table("bodhi_update_groups")
    # ### end Alembic commands ###
