"""Extend OSHScanModel

Revision ID: 9f84a235ccbf
Revises: 2e5ad4cbfa33
Create Date: 2024-10-30 11:03:25.002071

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9f84a235ccbf"
down_revision = "2e5ad4cbfa33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("submitted_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "submitted_time")
    # ### end Alembic commands ###
