"""Store submit time of SRPM builds

Revision ID: a0e48c400be4
Revises: 521433a1fdb0
Create Date: 2020-09-01 06:52:19.289499

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a0e48c400be4"
down_revision = "521433a1fdb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "srpm_builds",
        sa.Column("build_submitted_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("srpm_builds", "build_submitted_time")
    # ### end Alembic commands ###
