"""fix(tf): add canceled state

Revision ID: ab4c11acf5e1
Revises: a3a17014c282
Create Date: 2024-02-11 21:53:26.180964

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ab4c11acf5e1"
down_revision = "a3a17014c282"
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE testingfarmresult ADD VALUE 'canceled'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
