"""Add sidetag and nvr fields to KojiBuildTargetModel

Revision ID: adb6be5bc358
Revises: 242a0cdb6d23
Create Date: 2024-10-20 15:47:45.454965

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "adb6be5bc358"
down_revision = "242a0cdb6d23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "koji_build_targets",
        sa.Column("sidetag", sa.String(), nullable=True),
    )
    op.add_column("koji_build_targets", sa.Column("nvr", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("koji_build_targets", "nvr")
    op.drop_column("koji_build_targets", "sidetag")
    # ### end Alembic commands ###
