"""Move commit_sha to project_events

Revision ID: af00a7f19025
Revises: 4033221ea50c
Create Date: 2023-05-26 11:38:41.607843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af00a7f19025"
down_revision = "4033221ea50c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_events", sa.Column("commit_sha", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_project_events_commit_sha"),
        "project_events",
        ["commit_sha"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_events_commit_sha"), table_name="project_events")
    op.drop_column("project_events", "commit_sha")
    # ### end Alembic commands ###
