"""Add Anitya related models

Revision ID: b43ff6137622
Revises: 64a51b961c28
Create Date: 2024-08-01 10:37:55.286362

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b43ff6137622"
down_revision = "64a51b961c28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anitya_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("project_name", sa.String(), nullable=True),
        sa.Column("package", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anitya_projects_project_id"),
        "anitya_projects",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "anitya_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["anitya_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anitya_versions_project_id"),
        "anitya_versions",
        ["project_id"],
        unique=False,
    )
    # add the event type
    op.execute("ALTER TYPE projecteventtype ADD VALUE 'anitya_version'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_anitya_versions_project_id"), table_name="anitya_versions")
    op.drop_table("anitya_versions")
    op.drop_index(op.f("ix_anitya_projects_project_id"), table_name="anitya_projects")
    op.drop_table("anitya_projects")
    # ### end Alembic commands ###
