"""Add error_msg to Log Detective

Revision ID: b4e11a52ea52
Revises: b705ac677052
Create Date: 2026-07-08 14:10:52.273970

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4e11a52ea52"
down_revision = "b705ac677052"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log_detective_run", sa.Column("error_msg", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log_detective_run", "error_msg")
    # ### end Alembic commands ###
