"""Adding Log Detective Run Group table

Revision ID: bb4dd06bb4ab
Revises: 108167f43395
Create Date: 2025-12-17 08:29:58.141317

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bb4dd06bb4ab"
down_revision = "108167f43395"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_detective_run_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submitted_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "log_detective_run", sa.Column("log_detective_run_group_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_log_detective_run_log_detective_run_group_id"),
        "log_detective_run",
        ["log_detective_run_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_log_detective_run_group_id",
        "log_detective_run",
        "log_detective_run_groups",
        ["log_detective_run_group_id"],
        ["id"],
    )
    op.add_column("pipelines", sa.Column("log_detective_run_group_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_pipelines_log_detective_run_group_id"),
        "pipelines",
        ["log_detective_run_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_log_detective_run_group_pipeline_id",
        "pipelines",
        "log_detective_run_groups",
        ["log_detective_run_group_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_log_detective_run_group_pipeline_id", "pipelines", type_="foreignkey")
    op.drop_index(op.f("ix_pipelines_log_detective_run_group_id"), table_name="pipelines")
    op.drop_column("pipelines", "log_detective_run_group_id")
    op.drop_constraint("fk_log_detective_run_group_id", "log_detective_run", type_="foreignkey")
    op.drop_index(
        op.f("ix_log_detective_run_log_detective_run_group_id"), table_name="log_detective_run"
    )
    op.drop_column("log_detective_run", "log_detective_run_group_id")
    op.drop_table("log_detective_run_groups")
    # ### end Alembic commands ###
