"""add_whitelist

Revision ID: c2d1abe6f07c
Revises: 61d0f32eda4b
Create Date: 2020-03-17 09:48:36.937739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2d1abe6f07c"
down_revision = "61d0f32eda4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whitelist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_whitelist_status"), "whitelist", ["status"], unique=False)
    op.create_index(
        op.f("ix_whitelist_account_name"), "whitelist", ["account_name"], unique=False
    )
    op.drop_column("copr_builds", "logs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copr_builds", sa.Column("logs", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_whitelist_account_name"), table_name="whitelist")
    op.drop_index(op.f("ix_whitelist_status"), table_name="whitelist")
    op.drop_table("whitelist")
    # ### end Alembic commands ###
