"""Add build_submission_stdout for Koji build targets

Revision ID: c91276691f38
Revises: 6f936840164c
Create Date: 2024-11-25 15:43:02.738073

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c91276691f38"
down_revision = "6f936840164c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "koji_build_targets", sa.Column("build_submission_stdout", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("koji_build_targets", "build_submission_stdout")
    # ### end Alembic commands ###
