"""Adding log_detective_run_groups and modifying log_detective_run table

Revision ID: d408de018a66
Revises: 108167f43395
Create Date: 2026-01-06 13:19:04.386945

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d408de018a66"
down_revision = "108167f43395"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_detective_run_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submitted_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("log_detective_run", sa.Column("target", sa.String(), nullable=True))
    op.add_column("log_detective_run", sa.Column("analysis_id", sa.String(), nullable=False))
    op.add_column(
        "log_detective_run", sa.Column("log_detective_run_group_id", sa.Integer(), nullable=True)
    )
    op.alter_column("log_detective_run", "identifier", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("log_detective_run_identifier_key", "log_detective_run", type_="unique")
    op.create_index(
        op.f("ix_log_detective_run_log_detective_run_group_id"),
        "log_detective_run",
        ["log_detective_run_group_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_log_detective_run_analysis_id", "log_detective_run", ["analysis_id"]
    )
    op.create_foreign_key(
        "fk_log_detective_run_log_detective_run_groups_id",
        "log_detective_run",
        "log_detective_run_groups",
        ["log_detective_run_group_id"],
        ["id"],
    )
    op.add_column("pipelines", sa.Column("log_detective_run_group_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_pipelines_log_detective_run_group_id"),
        "pipelines",
        ["log_detective_run_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_pipelines_log_detective_run_groups_id",
        "pipelines",
        "log_detective_run_groups",
        ["log_detective_run_group_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_pipelines_log_detective_run_groups_id", "pipelines", type_="foreignkey")
    op.drop_index(op.f("ix_pipelines_log_detective_run_group_id"), table_name="pipelines")
    op.drop_column("pipelines", "log_detective_run_group_id")
    op.drop_constraint(
        "fk_log_detective_run_log_detective_run_groups_id", "log_detective_run", type_="foreignkey"
    )
    op.drop_constraint("uq_log_detective_run_analysis_id", "log_detective_run", type_="unique")
    op.drop_index(
        op.f("ix_log_detective_run_log_detective_run_group_id"), table_name="log_detective_run"
    )
    op.create_unique_constraint(
        "log_detective_run_identifier_key",
        "log_detective_run",
        ["identifier"],
        postgresql_nulls_not_distinct=False,
    )
    # This may cause issues if we downgrade after leaving records with empty `identifier`
    # In such a case, fill the column with dummy values before downgrade
    op.alter_column("log_detective_run", "identifier", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("log_detective_run", "log_detective_run_group_id")
    op.drop_column("log_detective_run", "analysis_id")
    op.drop_column("log_detective_run", "target")
    op.drop_table("log_detective_run_groups")
    # ### end Alembic commands ###
