"""

Revision ID: d4fcd3075c10
Revises: 43882376fe16
Create Date: 2025-12-03 13:04:43.840629

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4fcd3075c10"
down_revision = "43882376fe16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the ENUM type from projecteventtype to projecteventmodeltype
    op.execute("ALTER TYPE projecteventtype RENAME TO projecteventmodeltype")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the ENUM type back from projecteventmodeltype to projecteventtype
    op.execute("ALTER TYPE projecteventmodeltype RENAME TO projecteventtype")
    # ### end Alembic commands ###
