"""Add identifier to copr build

Revision ID: d625d6c1122f
Revises: c91276691f38
Create Date: 2024-11-22 13:05:49.763917

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d625d6c1122f"
down_revision = "c91276691f38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copr_build_targets", sa.Column("identifier", sa.String(), default="", nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copr_build_targets", "identifier")
    # ### end Alembic commands ###
