"""Add a table for github installations

Revision ID: d7c2f99cd14d
Revises: d90948124e46
Create Date: 2020-04-01 10:56:59.210206

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d7c2f99cd14d"
down_revision = "d90948124e46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_login", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("account_url", sa.String(), nullable=True),
        sa.Column("account_type", sa.String(), nullable=True),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("sender_login", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "repositories",
            sa.ARRAY(sa.Integer(), as_tuple=sa.ForeignKey("git_projects.id")),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_installations")
    # ### end Alembic commands ###
