"""add package name to the pipeline

Revision ID: db64a37ff1c6
Revises: af00a7f19025
Create Date: 2023-08-22 11:28:07.466045

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "db64a37ff1c6"
down_revision = "af00a7f19025"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pipelines", sa.Column("package_name", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_pipelines_package_name"),
        "pipelines",
        ["package_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipelines_package_name"), table_name="pipelines")
    op.drop_column("pipelines", "package_name")
    # ### end Alembic commands ###
