"""Added instance_url field to GitProject

Revision ID: e35bb9ce7313
Revises: a0e48c400be4
Create Date: 2020-11-05 11:33:02.769607

"""

from typing import TYPE_CHECKING
from urllib.parse import urlparse

import sqlalchemy as sa
from sqlalchemy import Column, Integer, String, orm
from sqlalchemy.ext.declarative import declarative_base

from alembic import op

# https://github.com/python/mypy/issues/2477#issuecomment-313984522 ^_^
if TYPE_CHECKING:
    Base = object
else:
    Base = declarative_base()

# revision identifiers, used by Alembic.
revision = "e35bb9ce7313"
down_revision = "a0e48c400be4"
branch_labels = None
depends_on = None


class GitProjectModel(Base):
    __tablename__ = "git_projects"
    id = Column(Integer, primary_key=True)

    project_url = Column(String)
    instance_url = Column(String, nullable=False)


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    op.add_column("git_projects", sa.Column("instance_url", sa.String(), nullable=True))
    for git_project in session.query(GitProjectModel):
        git_project.instance_url = urlparse(git_project.project_url).hostname
    session.commit()
    op.alter_column("git_projects", "instance_url", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("git_projects", "instance_url")
    # ### end Alembic commands ###
