"""Add issues_added_count for OSHScanModel

Revision ID: f69687c314c5
Revises: 4387d6ab90e9
Create Date: 2024-11-14 14:02:08.691590

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f69687c314c5"
down_revision = "4387d6ab90e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("issues_added_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "issues_added_count")
    # ### end Alembic commands ###
