# For running tests locally, see check_in_container target in Makefile

FROM docker.io/usercont/packit-service-worker:dev

ARG SOURCE_BRANCH
RUN  if [[ -z $SOURCE_BRANCH ]]; then \
echo -e "\nMissing SOURCE_BRANCH build argument! Please add \
\"--build-arg SOURCE_BRANCH=<val>\" to the build command to specify it!\n\
This is the branch used when installing other Packit projects (e.g. ogr, packit).\n" && exit 1;\
fi

# Since we use worker base image, we need to install service deps manually
RUN ansible-playbook -vv -c local -i localhost, files/install-deps.yaml

RUN set -ex; mkdir -p ${HOME}/.config \
    && ln -s $(pwd)/files/packit-service.yaml ${HOME}/.config/packit-service.yaml \
    && ansible-playbook -vv -c local -i localhost, files/recipe-tests.yaml

# we are doing the same here as in worker Df so that we don't need to rerun the
# playbook above for every code change: iterating fast <3
COPY . ./
