# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# Tasks common to all images
-
- name: Create /usr/share/packit
  ansible.builtin.file:
    state: directory
    path: /usr/share/packit
    mode: 0775
- name: make packit home dir
  ansible.builtin.file:
    state: directory
    path: "{{ home_path }}"
    mode: 0776
- name: stat {{ packit_service_path }}
  ansible.builtin.stat:
    path: "{{ packit_service_path }}"
  tags:
    - no-cache
  register: src_path
- name: Let's make sure {{ packit_service_path }} is present
  ansible.builtin.assert:
    that:
      - src_path.stat.isdir
- name: Install packit-service from {{ packit_service_path }}
  ansible.builtin.pip:
    name: "{{ packit_service_path }}"
- name: Clean all the cache files (especially pip)
  ansible.builtin.file:
    state: absent
    path: ~/.cache/
- name: Copy setup_env_in_openshift.sh
  ansible.builtin.copy:
    src: setup_env_in_openshift.sh
    dest: /usr/bin/setup_env_in_openshift.sh
    mode: 0775
