# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

- name: Copy run_server.sh
  ansible.builtin.copy:
    src: run_server.sh
    dest: /usr/bin/run_server.sh
    mode: 0775
