[Container]
## Secrets are not available in the repo, populate them and mount them
## as follows
#Volume=../../secrets/packit/dev/packit-service.yaml:/home/packit/.config/packit-service.yaml:ro,z
#Volume=../../secrets/packit/dev/fedora.keytab:/secrets/fedora.keytab:ro,z
#Volume=../../secrets/packit/dev/fullchain.pem:/secrets/fullchain.pem:ro,z
#Volume=../../secrets/packit/dev/privkey.pem:/secrets/privkey.pem:ro,z
