[Unit]
After=postgres.container
Requires=postgres.container

[Container]
Environment=POSTGRESQL_HOST=postgres
Environment=POSTGRESQL_USER=packit
Environment=POSTGRESQL_DATABASE=packit
Network=postgres.network
