# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check packit-service deployment
  hosts: all
  vars:
    deployment_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/packit/deployment'].src_dir }}"
    as_root: true # needs to run as root in zuul
  tasks:
    - name: Check deployment
      ansible.builtin.import_playbook: "{{ deployment_dir }}/playbooks/check.yml"
      environment:
        DEPLOYMENT: dev
        ANSIBLE_STDOUT_CALLBACK: debug
      become: "{{ as_root }}"
