---
- name: Install dependencies for packit-service.
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
  tasks:
    - import_tasks: tasks/process-source-branch.yaml
    - name: Install all RPM/python packages needed to run packit-service.
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - python3-mod_wsgi
          - python3-click
          - git # setuptools-scm
          # httpd & deps
          - httpd
          - mod_md
          - mod_ssl
          - nss_wrapper
          #- python3-packit # temporary workaround for sake of marhsmallow
          - python3-pip # not included in base fedora:31 image, needed for next task
          # temporary dependencies
          - krb5-devel
          - gcc
          - python3-devel
          - python3-alembic
          - python3-sqlalchemy
          - python3-prometheus_client
          - python3-psycopg2
          - python3-celery
          - python3-redis # celery[redis]
          - python3-boto3 # celery[sqs]
          - python3-pycurl # celery[sqs]
          - python3-lazy-object-proxy
          - python3-flask-restx
          - python3-flexmock # because of the hack during the alembic upgrade
          # (see d90948124e46_add_tables_for_triggers_koji_and_tests.py )
          - dnf-plugins-core
          - python-jwt
        state: present
    - import_tasks: tasks/install-ogr-deps.yaml
    - import_tasks: tasks/install-packit-deps.yaml
    - name: Install pip deps
      pip:
        name:
          - persistentdict # still needed by one Alembic migration script
          - sentry-sdk[flask]==0.18.0
        executable: pip3

    # --no-deps: to fail instead of installing from PyPI when we forget to add some dependency to packit.spec
    - name: pip install packit & ogr with --no-deps
      pip:
        name:
          - git+https://github.com/packit/packit.git@{{ source_branch }}
          # ogr has only master branch
          - git+https://github.com/packit/ogr.git
        executable: pip3
        extra_args: --no-deps
    - name: Chek if all pip packages have all dependencies installed
      command: pip check
