---
- name: Install dependencies for packit-service worker.
  hosts: all
  tasks:
  - name: Install all RPM/python packages needed to run packit-service worker.
    dnf:
      name:
      - python3-ipdb  # for easy debugging
      - nss_wrapper  # openshift anyuid passwd madness
      - python3-celery # (#107)
      - python3-redis
      - redis  # redis-cli for debugging
      - origin-clients # for sandcastle
      - python3-kubernetes # for sandcastle
      - python3-requests
      state: present
  - name: Install pip deps
    pip:
      name:
      - git+https://github.com/packit-service/sandcastle.git
      - git+https://github.com/packit-service/ogr.git
      - persistentdict
      # "We recommend you update your SDK from version 0.12.2 to version 0.12.3"
      - sentry-sdk==0.12.3
      executable: pip3
