---
- name: Install dependencies for packit-service worker.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run packit-service worker.
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - nss_wrapper # openshift anyuid passwd madness
          - redis # redis-cli for debugging
          - origin-clients # for sandcastle
          - python3-kubernetes # for sandcastle
          - python3-fedora # to access FAS
          - python3-requests
          - python3-alembic
          - python3-sqlalchemy
          - python3-psycopg2
        state: present
    - name: Install pip deps
      pip:
        name:
          - git+https://github.com/packit-service/sandcastle.git
          - persistentdict
          # "We recommend you update your SDK from version 0.12.3 to version 0.14.0"
          - sentry-sdk==0.14.0
        executable: pip3
