# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: This is a recipe for how to cook with packit-service
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    packit_service_path: /src
  tasks:
    - import_tasks: tasks/common.yaml
    - import_tasks: tasks/httpd.yaml
