---
# This playbook is running tests inside Zuul
- name: Run packit-service tests
  hosts: all
  tasks:
    - name: Creates zuul secrets directory
      file:
        path: "{{ zuul.project.src_dir }}/secrets/packit/dev"
        state: directory
    - name: Run tests which are executed within openshift
      command: make check-inside-openshift-zuul
      args:
        chdir: "{{ zuul.project.src_dir }}"
      become: true
      environment:
        SOURCE_BRANCH: "{{ zuul.branch }}"
