# MIT License
#
# Copyright (c) 2018-2019 Red Hat, Inc.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import pytest
from flexmock import flexmock

from packit.actions import ActionName
from packit.config import JobConfig, JobType, JobConfigTriggerType
from packit.config.job_config import JobMetadataConfig
from packit_service.service.events import TheJobTriggerType
from packit_service.worker.handlers import (
    PullRequestCoprBuildHandler,
    ProposeDownstreamHandler,
    CoprBuildStartHandler,
    CoprBuildEndHandler,
    TestingFarmResultsHandler,
)
from packit_service.worker.handlers.fedmsg_handlers import KojiBuildReportHandler
from packit_service.worker.handlers.github_handlers import (
    PullRequestGithubKojiBuildHandler,
    PushGithubKojiBuildHandler,
    PushCoprBuildHandler,
    ReleaseGithubKojiBuildHandler,
    GitHubPullRequestCommentCoprBuildHandler,
    GitHubIssueCommentProposeUpdateHandler,
)
from packit_service.worker.jobs import (
    get_handlers_for_event,
    get_config_for_handler_kls,
)


@pytest.mark.parametrize(
    "trigger,db_trigger,jobs,result",
    [
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [],
            set(),
            id="nothing_configured",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {PullRequestCoprBuildHandler},
            id="config=copr_build@trigger=pull_request",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {PullRequestCoprBuildHandler},
            id="config=build@trigger=pull_request",
        ),
        pytest.param(
            TheJobTriggerType.push,
            flexmock(job_config_trigger_type=JobConfigTriggerType.commit),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.commit,
                )
            ],
            {PushCoprBuildHandler},
            id="config=copr_build_on_push@trigger=push",
        ),
        pytest.param(
            TheJobTriggerType.commit,
            flexmock(job_config_trigger_type=JobConfigTriggerType.commit),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.commit,
                )
            ],
            {PushCoprBuildHandler},
            id="config=copr_build_on_push@trigger=commit",
        ),
        pytest.param(
            TheJobTriggerType.release,
            flexmock(job_config_trigger_type=JobConfigTriggerType.release),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                )
            ],
            {ProposeDownstreamHandler},
            id="propose_downstream",
        ),
        pytest.param(
            TheJobTriggerType.copr_start,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {CoprBuildStartHandler},
            id="config=copr_build@trigger=copr_start",
        ),
        pytest.param(
            TheJobTriggerType.copr_end,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {CoprBuildEndHandler},
            id="config=copr_build@trigger=copr_end",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.release,
                ),
            ],
            {PullRequestCoprBuildHandler},
            id="config=copr_build_on_pull_request_and_release@trigger=pull_request",
        ),
        pytest.param(
            TheJobTriggerType.copr_end,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.release,
                ),
            ],
            {CoprBuildEndHandler},
            id="config=copr_build_on_pull_request_and_release@trigger=copr_end",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {PullRequestCoprBuildHandler},
            id="config=tests@trigger=pull_request",
        ),
        pytest.param(
            TheJobTriggerType.copr_start,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {CoprBuildStartHandler},
            id="config=tests@trigger=copr_start",
        ),
        pytest.param(
            TheJobTriggerType.copr_end,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {CoprBuildEndHandler},
            id="config=tests@trigger=copr_end",
        ),
        pytest.param(
            TheJobTriggerType.testing_farm_results,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            {TestingFarmResultsHandler},
            id="config=tests@trigger=testing_farm_results",
        ),
        pytest.param(
            TheJobTriggerType.testing_farm_results,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {TestingFarmResultsHandler},
            id="config=tests_and_copr_build@trigger=testing_farm_results",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {PullRequestCoprBuildHandler},
            id="config=tests_and_copr_build@trigger=pull_request",
        ),
        pytest.param(
            TheJobTriggerType.copr_start,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {CoprBuildStartHandler},
            id="config=tests_and_copr_build@trigger=copr_start",
        ),
        pytest.param(
            TheJobTriggerType.copr_start,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.tests,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                ),
                JobConfig(
                    type=JobType.sync_from_downstream,
                    trigger=JobConfigTriggerType.commit,
                ),
            ],
            {CoprBuildStartHandler},
            id="config=tests_and_copr_build_and_propose_and_sync@trigger=copr_start",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {PullRequestGithubKojiBuildHandler},
            id="config=production_build@trigger=pull_request",
        ),
        pytest.param(
            TheJobTriggerType.push,
            flexmock(job_config_trigger_type=JobConfigTriggerType.commit),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                ),
            ],
            {PushGithubKojiBuildHandler},
            id="config=production_build@trigger=push",
        ),
        pytest.param(
            TheJobTriggerType.commit,
            flexmock(job_config_trigger_type=JobConfigTriggerType.commit),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                ),
            ],
            {PushGithubKojiBuildHandler},
            id="config=production_build@trigger=commit",
        ),
        pytest.param(
            TheJobTriggerType.release,
            flexmock(job_config_trigger_type=JobConfigTriggerType.release),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.release,
                ),
            ],
            {ReleaseGithubKojiBuildHandler},
            id="config=production_build@trigger=release",
        ),
        pytest.param(
            TheJobTriggerType.push,
            flexmock(job_config_trigger_type=JobConfigTriggerType.commit),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {PushGithubKojiBuildHandler},
            id="config=production_build_on_pull_request_and_commit@trigger=commit",
        ),
        pytest.param(
            TheJobTriggerType.koji_results,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {KojiBuildReportHandler},
            id="config=production_build@trigger=koji_results",
        ),
        pytest.param(
            TheJobTriggerType.koji_results,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            set(),
            id="config=copr_build@trigger=koji_results",
        ),
        pytest.param(
            TheJobTriggerType.koji_results,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            {KojiBuildReportHandler},
            id="config=production_build_and_copr_build@trigger=koji_results",
        ),
        pytest.param(
            TheJobTriggerType.issue_comment,
            flexmock(job_config_trigger_type=None),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                ),
            ],
            {GitHubIssueCommentProposeUpdateHandler},
            id="config=propose_downstream@trigger=issue_comment",
        ),
        pytest.param(
            TheJobTriggerType.pull_request,
            flexmock(job_config_trigger_type=JobConfigTriggerType.pull_request),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                    metadata=JobMetadataConfig(targets=["fedora-rawhide-x86_64"]),
                    actions={ActionName.post_upstream_clone: "ls /*"},
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                    metadata=JobMetadataConfig(targets=["fedora-32-x86_64"]),
                    actions={ActionName.post_upstream_clone: 'bash -c "ls /*"'},
                ),
            ],
            {PullRequestCoprBuildHandler},
            id="config=multiple_copr_builds_for_pr@trigger=pull_request",
        ),
    ],
)
def test_get_handlers_for_event(trigger, db_trigger, jobs, result):
    event_handlers = set(
        get_handlers_for_event(
            event=flexmock(trigger=trigger, db_trigger=db_trigger),
            package_config=flexmock(jobs=jobs),
        )
    )
    assert event_handlers == result


@pytest.mark.parametrize(
    "handler_kls,event,jobs,result_job_config",
    [
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            id="copr_build_for_pr",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [JobConfig(type=JobType.tests, trigger=JobConfigTriggerType.pull_request)],
            [JobConfig(type=JobType.tests, trigger=JobConfigTriggerType.pull_request)],
            id="copr_build_for_pr_when_test_defined",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.tests, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
            ],
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            id="copr_build_for_pr_when_test_and_build_defined",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.tests, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.release
                ),
            ],
            [JobConfig(type=JobType.tests, trigger=JobConfigTriggerType.pull_request)],
            id="copr_build_for_pr_when_test_for_pr_and_build_for_release_are_defined",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.commit,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.commit
                ),
            ),
            [
                JobConfig(
                    type=JobType.tests, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
            ],
            [],
            id="copr_build_for_commit_when_test_and_build_are_defined_for_pr",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.commit,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.commit
                ),
            ),
            [
                JobConfig(
                    type=JobType.tests, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(type=JobType.copr_build, trigger=JobConfigTriggerType.commit),
            ],
            [JobConfig(type=JobType.copr_build, trigger=JobConfigTriggerType.commit)],
            id="copr_build_for_commit_when_test_and_build_are_defined_for_pr_and_build_for_push",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.commit,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.commit
                ),
            ),
            [
                JobConfig(
                    type=JobType.tests, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.commit,
                    metadata=JobMetadataConfig(branch="a"),
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.commit,
                    metadata=JobMetadataConfig(branch="b"),
                ),
            ],
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.commit,
                    metadata=JobMetadataConfig(branch="a"),
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.commit,
                    metadata=JobMetadataConfig(branch="b"),
                ),
            ],
            id="copr_build_for_commit_when_test_and_build_are_defined_for_pr_and_build_for_push"
            "@more_branches",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            id="copr_build_for_pr_when_test_build_and_koji_build_defined",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.build, trigger=JobConfigTriggerType.pull_request
                ),
            ],
            id="copr_build_for_pr_multiple_defs",
        ),
        pytest.param(
            PullRequestGithubKojiBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            id="koji_build_for_pr",
        ),
        pytest.param(
            PullRequestGithubKojiBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.commit,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.commit
                ),
            ),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                    metadata=JobMetadataConfig(branch="some-branch"),
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                    metadata=JobMetadataConfig(branch="some-branch"),
                ),
            ],
            id="koji_build_for_commit_when_pr_and_branch_configured",
        ),
        pytest.param(
            ProposeDownstreamHandler,
            flexmock(
                trigger=TheJobTriggerType.release,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.release
                ),
            ),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                )
            ],
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                )
            ],
            id="propose_downstream",
        ),
        pytest.param(
            ProposeDownstreamHandler,
            flexmock(
                trigger=TheJobTriggerType.release,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.release
                ),
            ),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                    metadata=JobMetadataConfig(targets=["a"]),
                ),
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                    metadata=JobMetadataConfig(targets=["b"]),
                ),
            ],
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                    metadata=JobMetadataConfig(targets=["a"]),
                ),
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                    metadata=JobMetadataConfig(targets=["b"]),
                ),
            ],
            id="propose_downstream_multiple",
        ),
        pytest.param(
            CoprBuildEndHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            id="copr_build_end",
        ),
        pytest.param(
            CoprBuildEndHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [JobConfig(type=JobType.build, trigger=JobConfigTriggerType.pull_request)],
            [JobConfig(type=JobType.build, trigger=JobConfigTriggerType.pull_request)],
            id="copr_build_end_with_build_alias",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            id="koji_results",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                )
            ],
            [],
            id="koji_results_when_copr_build_defined",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [JobConfig(type=JobType.tests, trigger=JobConfigTriggerType.pull_request)],
            [],
            id="koji_results_when_test_defined",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.tests, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.copr_build, trigger=JobConfigTriggerType.pull_request
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            id="koji_results_when_test_and_copr_build_defined",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.release,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                ),
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                )
            ],
            id="koji_results_when_multiple_triggers_defined",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.release
                ),
            ),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.release,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                ),
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.release,
                )
            ],
            id="koji_results_for_release_when_multiple_triggers_defined",
        ),
        pytest.param(
            KojiBuildReportHandler,
            flexmock(
                trigger=TheJobTriggerType.koji_results,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.commit
                ),
            ),
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.pull_request,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.release,
                ),
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                ),
            ],
            [
                JobConfig(
                    type=JobType.production_build,
                    trigger=JobConfigTriggerType.commit,
                )
            ],
            id="koji_results_for_commit_when_multiple_triggers_defined",
        ),
        pytest.param(
            GitHubPullRequestCommentCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pr_comment,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [JobConfig(type=JobType.tests, trigger=JobConfigTriggerType.pull_request)],
            [JobConfig(type=JobType.tests, trigger=JobConfigTriggerType.pull_request)],
            id="pr_comment_when_test_defined",
        ),
        pytest.param(
            ProposeDownstreamHandler,
            flexmock(
                trigger=TheJobTriggerType.release,
                db_trigger=flexmock(job_config_trigger_type=None),
            ),
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                )
            ],
            [
                JobConfig(
                    type=JobType.propose_downstream,
                    trigger=JobConfigTriggerType.release,
                )
            ],
            id="issue_comment_when_propose_downstream_defined",
        ),
        pytest.param(
            PullRequestCoprBuildHandler,
            flexmock(
                trigger=TheJobTriggerType.pull_request,
                db_trigger=flexmock(
                    job_config_trigger_type=JobConfigTriggerType.pull_request
                ),
            ),
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                    metadata=JobMetadataConfig(targets=["fedora-rawhide-x86_64"]),
                    actions={ActionName.post_upstream_clone: "ls /*"},
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                    metadata=JobMetadataConfig(targets=["fedora-32-x86_64"]),
                    actions={ActionName.post_upstream_clone: 'bash -c "ls /*"'},
                ),
            ],
            [
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                    metadata=JobMetadataConfig(targets=["fedora-rawhide-x86_64"]),
                    actions={ActionName.post_upstream_clone: "ls /*"},
                ),
                JobConfig(
                    type=JobType.copr_build,
                    trigger=JobConfigTriggerType.pull_request,
                    metadata=JobMetadataConfig(targets=["fedora-32-x86_64"]),
                    actions={ActionName.post_upstream_clone: 'bash -c "ls /*"'},
                ),
            ],
            id="multiple_copr_builds_for_pr",
        ),
    ],
)
def test_get_config_for_handler_kls(handler_kls, event, jobs, result_job_config):
    job_config = get_config_for_handler_kls(
        handler_kls=handler_kls,
        event=event,
        package_config=flexmock(jobs=jobs),
    )
    assert job_config == result_job_config
